
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models;
using Core.Operations.ApplicationSettings.Extras;
namespace Core.Models.Mappings
{
    public static partial class ApplicationSettingExtensions
    {
        private static ApplicationSettingRow toApplicationSettingRow(ApplicationSetting model, ApplicationSettingRow message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            message.Value = model.Value;
            return message;
        }
        public static ApplicationSetting updateFromApplicationSettingRow(ApplicationSettingRow message, ApplicationSetting model)
        {
            model.Name=message.Name;
            model.Value=message.Value;
            return model;
        }
    }
}

