
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models.Exceptions;
using Core.Operations.Errors.Extras;
namespace Core.Models.Mappings
{
    public static partial class ErrorExtensions
    {
        private static ErrorRow toErrorRow(Error model, ErrorRow message)
        {
            message.Id = model.Id;
            message.Type = model.Type;
            message.Message = model.Message;
            message.User = model.User;
            return message;
        }
        public static Error updateFromErrorRow(ErrorRow message, Error model)
        {
            model.Type=message.Type;
            model.Message=message.Message;
            model.User=message.User;
            return model;
        }
    }
}

