
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models.Scratch;
using Core.Operations.Projects.Extras;
namespace Core.Models.Mappings
{
    public static partial class ProjectExtensions
    {
        private static ProjectDetail toProjectDetail(Project model, ProjectDetail message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            message.TeamId = model.TeamId;
            return message;
        }
        public static Project updateFromProjectDetail(ProjectDetail message, Project model)
        {
            model.Name=message.Name;
            model.TeamId=message.TeamId;
            return model;
        }
    }
}

