
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models.Identity;
using Core.Operations.Roles.Extras;
namespace Core.Models.Mappings
{
    public static partial class RoleExtensions
    {
        private static RoleDetail toRoleDetail(Role model, RoleDetail message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            return message;
        }
        public static Role updateFromRoleDetail(RoleDetail message, Role model)
        {
            model.Name=message.Name;
            return model;
        }
    }
}

