
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models.Scratch;
using Core.Operations.Teams.Extras;
namespace Core.Models.Mappings
{
    public static partial class TeamExtensions
    {
        private static TeamRow toTeamRow(Team model, TeamRow message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            return message;
        }
        public static Team updateFromTeamRow(TeamRow message, Team model)
        {
            model.Name=message.Name;
            return model;
        }
    }
}

