
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Voodoo.CodeGeneration.Models;
using Core.Operations.TestClasses.Extras;
namespace Core.Models.Mappings
{
    public static partial class TestClassExtensions
    {
        private static TestClassDetail toTestClassDetail(TestClass model, TestClassDetail message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            return message;
        }
        public static TestClass updateFromTestClassDetail(TestClassDetail message, TestClass model)
        {
            model.Name=message.Name;
            return model;
        }
    }
}

