
//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models.Identity;
using Core.Operations.Users.Extras;
namespace Core.Models.Mappings
{
    public static partial class UserExtensions
    {
        private static UserRow toUserRow(User model, UserRow message)
        {
            message.Id = model.Id;
            message.UserName = model.UserName;
            message.FirstName = model.FirstName;
            message.LastName = model.LastName;
            return message;
        }
        public static User updateFromUserRow(UserRow message, User model)
        {
            model.UserName=message.UserName;
            model.FirstName=message.FirstName;
            model.LastName=message.LastName;
            return model;
        }
    }
}

