//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************

using Voodoo.Infrastructure.Notations;

namespace Core.Operations.Lists
{
    [Client]
    public enum Lists
    {
        Role=1,
        Lists=2,
        SqlOperation=3,
    }
}
