//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************

using System.Collections.Generic;
using Voodoo.Messages;

namespace Core.Operations.Lists
{
    public class ListsResponse :Response
    {
        public List<IListItem> Roles {get;set;}
        public List<IListItem> Lists {get;set;}
        public List<IListItem> SqlOperations {get;set;}
        
        public ListsResponse()
        {
            Roles = new List<IListItem>();
            Lists = new List<IListItem>();
            SqlOperations = new List<IListItem>();
        }
    }
}
