//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Core;
using Core.Models;
namespace Core.Operations.ApplicationSettings.Extras
{
    public static partial class ApplicationSettingExtensions
    {
        private static ApplicationSettingMessage toApplicationSettingMessage(ApplicationSetting model, ApplicationSettingMessage message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            message.Value = model.Value;
            
            return message;
        }
        public static ApplicationSetting updateFromApplicationSettingMessage(ApplicationSettingMessage message, ApplicationSetting model)
        {
            model.Name =message.Name;
            model.Value =message.Value;
            return model;
        }
        
    }
}

