//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
export interface IGroupingOfNameValuePair  {
name? : string;
id? : any;
data? : INameValuePair[];
}

export const EmptyIGroupingOfNameValuePair =
{
    name:undefined,
    id:undefined,
    data:undefined
}

export const IGroupingOfNameValuePairMetadata =
{
    name:
    {
    }
    ,id:
    {
    }
    ,data:
    {
    }
}

export interface INameValuePair  {
name? : string;
value? : string;
}

export const EmptyINameValuePair =
{
    name:undefined,
    value:undefined
}

export interface IApplicationSettingDetail  {
id? : number;
name? : string;
value? : string;
}

export const EmptyIApplicationSettingDetail =
{
    id:undefined,
    name:undefined,
    value:undefined
}

export const IApplicationSettingDetailMetadata =
{
    id:
    {
        displayFormat:'text',
        isHidden: true,
        propertyName:'Id',
        displayName:'Id'
        ,int:
        {
            shouldValidate:true
        }
    }
    ,name:
    {
        length:
        {
            shouldValidate:true
            ,min: 0
            ,max: 128
            ,message: '128 characters or less'
        }
    }
    ,value:
    {
        length:
        {
            shouldValidate:true
            ,min: 0
            ,max: 128
            ,message: '128 characters or less'
        }
        ,required:
        {
            shouldValidate:true
        }
    }
}

export interface IApplicationSettingListRequest  {
defaultSortMember? : string;
sortDirection? : string;
resetPaging? : boolean;
pageNumber? : number;
pageSize? : number;
sortMember? : string;
totalRecords? : number;
totalPages? : number;
}

export const EmptyIApplicationSettingListRequest =
{
    defaultSortMember:undefined,
    sortDirection:undefined,
    resetPaging:undefined,
    pageNumber:undefined,
    pageSize:undefined,
    sortMember:undefined,
    totalRecords:undefined,
    totalPages:undefined
}

export const IApplicationSettingListRequestMetadata =
{
    defaultSortMember:
    {
    }
    ,}
    
    export interface IApplicationSettingListResponse extends IResponse {
    state? : IGridState;
    data? : IApplicationSettingRow[];
    numberOfRowsEffected? : number;
    isOk? : boolean;
    hasLogicException? : boolean;
    message? : string;
    details? : INameValuePair[];
    exception? : any;
}

export const EmptyIApplicationSettingListResponse =
{
    state:undefined,
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IGridState  {
pageNumber? : number;
pageSize? : number;
totalRecords? : number;
totalPages? : number;
sortMember? : string;
sortDirection? : string;
defaultSortMember? : string;
resetPaging? : boolean;
}

export const EmptyIGridState =
{
    pageNumber:undefined,
    pageSize:undefined,
    totalRecords:undefined,
    totalPages:undefined,
    sortMember:undefined,
    sortDirection:undefined,
    defaultSortMember:undefined,
    resetPaging:undefined
}

export interface IApplicationSettingRow  {
id? : number;
name? : string;
value? : string;
}

export const EmptyIApplicationSettingRow =
{
    id:undefined,
    name:undefined,
    value:undefined
}

export interface IAppPrincipal  {
expiration? : Date;
refreshTime? : Date;
isAuthenticated? : boolean;
userName? : string;
userId? : number;
firstName? : string;
lastName? : string;
roles? : string[];
isAdmin? : boolean;
token? : string;
}

export const EmptyIAppPrincipal =
{
    expiration:undefined,
    refreshTime:undefined,
    isAuthenticated:undefined,
    userName:undefined,
    userId:undefined,
    firstName:undefined,
    lastName:undefined,
    roles:undefined,
    isAdmin:undefined,
    token:undefined
}

export const IAppPrincipalMetadata =
{
    expiration:
    {
        displayFormat:'date'
        ,date:
        {
            shouldValidate:true
        }
    }
    ,refreshTime:
    {
        displayFormat:'date'
        ,date:
        {
            shouldValidate:true
        }
    }
    ,isAuthenticated:
    {
    }
    ,userName:
    {
    }
    ,userId:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
    }
    ,firstName:
    {
    }
    ,lastName:
    {
    }
    ,roles:
    {
    }
    ,isAdmin:
    {
    }
    ,token:
    {
    }
}

export interface IClientInfo  {
timeZoneOffsetInMinutes? : number;
}

export const EmptyIClientInfo =
{
    timeZoneOffsetInMinutes:undefined
}

export const IClientInfoMetadata =
{
    timeZoneOffsetInMinutes:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
    }
}

export interface IEmptyRequest  {
}

export const EmptyIEmptyRequest =
{
}

export const IEmptyRequestMetadata =
{
}

export interface IErrorListRequest  {
searchText? : string;
defaultSortMember? : string;
sortDirection? : string;
resetPaging? : boolean;
pageNumber? : number;
pageSize? : number;
sortMember? : string;
totalRecords? : number;
totalPages? : number;
}

export const EmptyIErrorListRequest =
{
    searchText:undefined,
    defaultSortMember:undefined,
    sortDirection:undefined,
    resetPaging:undefined,
    pageNumber:undefined,
    pageSize:undefined,
    sortMember:undefined,
    totalRecords:undefined,
    totalPages:undefined
}

export const IErrorListRequestMetadata =
{
    searchText:
    {
    }
    ,defaultSortMember:
    {
    }
    ,}
    
    export interface IErrorListResponse extends IResponse {
    state? : IGridState;
    data? : IErrorRow[];
    numberOfRowsEffected? : number;
    isOk? : boolean;
    hasLogicException? : boolean;
    message? : string;
    details? : INameValuePair[];
    exception? : any;
}

export const EmptyIErrorListResponse =
{
    state:undefined,
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IErrorRow  {
id? : number;
creationDate? : Date;
type? : string;
message? : string;
user? : string;
}

export const EmptyIErrorRow =
{
    id:undefined,
    creationDate:undefined,
    type:undefined,
    message:undefined,
    user:undefined
}

export interface IIdRequest  {
id? : number;
}

export const EmptyIIdRequest =
{
    id:undefined
}

export const IIdRequestMetadata =
{
    id:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
    }
}

export enum Lists  {
Role = 1,
Lists = 2,
SqlOperation = 3
}
export const ListsMetadata =
{
}

export interface IListsRequest  {
includeInactive? : boolean;
lists? : Lists[];
}

export const EmptyIListsRequest =
{
    includeInactive:undefined,
    lists:undefined
}

export const IListsRequestMetadata =
{
    includeInactive:
    {
    }
    ,lists:
    {
    }
}

export interface IListsResponse extends IResponse {
roles? : IListItem[];
lists? : IListItem[];
sqlOperations? : IListItem[];
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIListsResponse =
{
    roles:undefined,
    lists:undefined,
    sqlOperations:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IListItem  {
value? : number;
name? : string;
}

export const EmptyIListItem =
{
    value:undefined,
    name:undefined
}

export interface IMemberDetail  {
id? : number;
name? : string;
title? : string;
requiredInt? : number;
optionalInt? : number;
requiredDate? : Date;
optionalDate? : Date;
requiredDecimal? : number;
optionalDecimal? : number;
managerId? : number;
}

export const EmptyIMemberDetail =
{
    id:undefined,
    name:undefined,
    title:undefined,
    requiredInt:undefined,
    optionalInt:undefined,
    requiredDate:undefined,
    optionalDate:undefined,
    requiredDecimal:undefined,
    optionalDecimal:undefined,
    managerId:undefined
}

export const IMemberDetailMetadata =
{
    id:
    {
        displayFormat:'text',
        isHidden: true,
        propertyName:'Id',
        displayName:'Id'
        ,int:
        {
            shouldValidate:true
        }
    }
    ,name:
    {
        length:
        {
            shouldValidate:true
            ,min: 0
            ,max: 128
            ,message: '128 characters or less'
        }
    }
    ,title:
    {
        length:
        {
            shouldValidate:true
            ,min: 0
            ,max: 128
            ,message: '128 characters or less'
        }
        ,required:
        {
            shouldValidate:true
        }
    }
    ,requiredInt:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
        ,required:
        {
            shouldValidate:true
        }
    }
    ,optionalInt:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
    }
    ,requiredDate:
    {
        displayFormat:'date'
        ,date:
        {
            shouldValidate:true
            ,min: new Date('1/1/1900')
            ,max: new Date('3/4/2050')
            ,message: 'date is either too far in the future or past'
        }
        ,required:
        {
            shouldValidate:true
        }
    }
    ,optionalDate:
    {
        displayFormat:'date'
        ,date:
        {
            shouldValidate:true
            ,min: new Date('1/1/1900')
            ,max: new Date('3/4/2050')
            ,message: 'date is either too far in the future or past'
        }
    }
    ,requiredDecimal:
    {
        displayFormat:'decimal'
        ,decimal:
        {
            shouldValidate:true
        }
        ,required:
        {
            shouldValidate:true
        }
    }
    ,optionalDecimal:
    {
        displayFormat:'decimal'
        ,decimal:
        {
            shouldValidate:true
        }
    }
    ,managerId:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
    }
}

export interface IMemberListRequest  {
defaultSortMember? : string;
sortDirection? : string;
resetPaging? : boolean;
pageNumber? : number;
pageSize? : number;
sortMember? : string;
totalRecords? : number;
totalPages? : number;
}

export const EmptyIMemberListRequest =
{
    defaultSortMember:undefined,
    sortDirection:undefined,
    resetPaging:undefined,
    pageNumber:undefined,
    pageSize:undefined,
    sortMember:undefined,
    totalRecords:undefined,
    totalPages:undefined
}

export const IMemberListRequestMetadata =
{
    defaultSortMember:
    {
    }
    ,}
    
    export interface IMemberListResponse extends IResponse {
    state? : IGridState;
    data? : IMemberRow[];
    numberOfRowsEffected? : number;
    isOk? : boolean;
    hasLogicException? : boolean;
    message? : string;
    details? : INameValuePair[];
    exception? : any;
}

export const EmptyIMemberListResponse =
{
    state:undefined,
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IMemberRow  {
id? : number;
name? : string;
title? : string;
requiredInt? : number;
optionalInt? : number;
}

export const EmptyIMemberRow =
{
    id:undefined,
    name:undefined,
    title:undefined,
    requiredInt:undefined,
    optionalInt:undefined
}

export interface IMobileErrorRequest  {
errorMsg? : string;
url? : string;
lineNumber? : string;
column? : string;
errorObject? : string;
}

export const EmptyIMobileErrorRequest =
{
    errorMsg:undefined,
    url:undefined,
    lineNumber:undefined,
    column:undefined,
    errorObject:undefined
}

export const IMobileErrorRequestMetadata =
{
    errorMsg:
    {
    }
    ,url:
    {
    }
    ,lineNumber:
    {
    }
    ,column:
    {
    }
    ,errorObject:
    {
    }
}

export interface INewItemResponse extends IResponse {
newItemId? : number;
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyINewItemResponse =
{
    newItemId:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IResponse  {
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIResponse =
{
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IResponseOfUserDetail extends IResponse {
data? : IUserDetail;
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIResponseOfUserDetail =
{
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IUserDetail  {
id? : number;
userName? : string;
clientId? : number;
firstName? : string;
lastName? : string;
lockoutEnabled? : boolean;
password? : string;
confirmPassword? : string;
roles? : IListItem[];
}

export const EmptyIUserDetail =
{
    id:undefined,
    userName:undefined,
    clientId:undefined,
    firstName:undefined,
    lastName:undefined,
    lockoutEnabled:undefined,
    password:undefined,
    confirmPassword:undefined,
    roles:undefined
}

export interface IResponseOfMemberDetail extends IResponse {
data? : IMemberDetail;
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIResponseOfMemberDetail =
{
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IResponseOfErrorDetail extends IResponse {
data? : IErrorDetail;
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIResponseOfErrorDetail =
{
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IErrorDetail  {
details? : string;
host? : string;
url? : string;
items? : IGroupingOfNameValuePair[];
id? : number;
creationDate? : Date;
type? : string;
message? : string;
user? : string;
}

export const EmptyIErrorDetail =
{
    details:undefined,
    host:undefined,
    url:undefined,
    items:undefined,
    id:undefined,
    creationDate:undefined,
    type:undefined,
    message:undefined,
    user:undefined
}

export interface IResponseOfAppPrincipal extends IResponse {
data? : IAppPrincipal;
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIResponseOfAppPrincipal =
{
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IResponseOfApplicationSettingDetail extends IResponse {
data? : IApplicationSettingDetail;
numberOfRowsEffected? : number;
isOk? : boolean;
hasLogicException? : boolean;
message? : string;
details? : INameValuePair[];
exception? : any;
}

export const EmptyIResponseOfApplicationSettingDetail =
{
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IUIMetadata  {
email? : IValidationMetaData;
length? : IValidationMetaData;
date? : IValidationMetaData;
integer? : IValidationMetaData;
decimal? : IValidationMetaData;
required? : IValidationMetaData;
propertyName? : string;
displayName? : string;
format? : string;
isReadOnly? : boolean;
isHidden? : boolean;
}

export const EmptyIUIMetadata =
{
    email:undefined,
    length:undefined,
    date:undefined,
    integer:undefined,
    decimal:undefined,
    required:undefined,
    propertyName:undefined,
    displayName:undefined,
    format:undefined,
    isReadOnly:undefined,
    isHidden:undefined
}

export const IUIMetadataMetadata =
{
    email:
    {
    }
    ,length:
    {
    }
    ,date:
    {
    }
    ,integer:
    {
    }
    ,decimal:
    {
    }
    ,required:
    {
    }
    ,propertyName:
    {
    }
    ,displayName:
    {
    }
    ,format:
    {
    }
    ,isReadOnly:
    {
    }
    ,isHidden:
    {
    }
}

export interface IValidationMetaData  {
shouldValidate? : boolean;
message? : string;
min? : any;
max? : any;
}

export const EmptyIValidationMetaData =
{
    shouldValidate:undefined,
    message:undefined,
    min:undefined,
    max:undefined
}

export interface IUserListRequest  {
searchText? : string;
defaultSortMember? : string;
id? : number;
sortDirection? : string;
resetPaging? : boolean;
pageNumber? : number;
pageSize? : number;
sortMember? : string;
totalRecords? : number;
totalPages? : number;
}

export const EmptyIUserListRequest =
{
    searchText:undefined,
    defaultSortMember:undefined,
    id:undefined,
    sortDirection:undefined,
    resetPaging:undefined,
    pageNumber:undefined,
    pageSize:undefined,
    sortMember:undefined,
    totalRecords:undefined,
    totalPages:undefined
}

export const IUserListRequestMetadata =
{
    searchText:
    {
    }
    ,defaultSortMember:
    {
    }
    ,id:
    {
        displayFormat:'int'
        ,int:
        {
            shouldValidate:true
        }
    }
    ,}
    
    export interface IUserListResponse extends IResponse {
    state? : IGridState;
    data? : IUserRow[];
    numberOfRowsEffected? : number;
    isOk? : boolean;
    hasLogicException? : boolean;
    message? : string;
    details? : INameValuePair[];
    exception? : any;
}

export const EmptyIUserListResponse =
{
    state:undefined,
    data:undefined,
    numberOfRowsEffected:undefined,
    isOk:undefined,
    hasLogicException:undefined,
    message:undefined,
    details:undefined,
    exception:undefined
}

export interface IUserRow  {
id? : number;
userName? : string;
clientId? : number;
firstName? : string;
lastName? : string;
roles? : string;
}

export const EmptyIUserRow =
{
    id:undefined,
    userName:undefined,
    clientId:undefined,
    firstName:undefined,
    lastName:undefined,
    roles:undefined
}

