//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************

using Core.Identity;
using Core.Models.Identity;

namespace Core.Operations.Users.Extras
{
    public static partial class UserExtensions
    {
        private static UserMessage toUserMessage(User model, UserMessage message)
        {
            message.Id = model.Id;
            message.UserName = model.UserName;
            message.FirstName = model.FirstName;
            message.LastName = model.LastName;
            
            return message;
        }
        public static User updateFromUserMessage(UserMessage message, User model)
        {
            model.UserName =message.UserName;
            model.FirstName =message.FirstName;
            model.LastName =message.LastName;
            return model;
        }
        private static UserDetail toUserDetail(User model, UserDetail message)
        {
            message.Id = model.Id;
            message.UserName = model.UserName;
            message.FirstName = model.FirstName;
            message.LastName = model.LastName;
            message.LockoutEnabled = model.LockoutEnabled;
            
            return message;
        }
        public static User updateFromUserDetail(UserDetail message, User model)
        {
            model.UserName =message.UserName;
            model.FirstName =message.FirstName;
            model.LastName =message.LastName;
            model.LockoutEnabled =message.LockoutEnabled;
            return model;
        }
        private static AppPrincipal toAppPrincipal(User model, AppPrincipal message)
        {
            message.UserName = model.UserName;
            message.FirstName = model.FirstName;
            message.LastName = model.LastName;
            
            return message;
        }
        public static User updateFromAppPrincipal(AppPrincipal message, User model)
        {
            model.UserName =message.UserName;
            model.FirstName =message.FirstName;
            model.LastName =message.LastName;
            return model;
        }
        
    }
}

