//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
namespace Fernweh.Core
{
    public partial class Constants
    {
        public partial class Messages
		{
			public const string Required = "required";
			public const string DateOutOfRange = "date is either too far in the future or past";
		}
    }
}