//***************************************************************
//This code was generated by a tool but it is ok to hand edit
//as long is what you're adding is a rest resource for an existing command or query
//The file gets rebuilt by building a distinct list of rest resources used
//on commands and queries
//***************************************************************
namespace Core
{
    public class RestResources
    {
        public const string ApplicationSetting = "ApplicationSetting";
        public const string ApplicationSettingList = "ApplicationSettingList";
        public const string CurrentUser = "CurrentUser";
        public const string ErrorLog = "ErrorLog";
        public const string ErrorLogList = "ErrorLogList";
        public const string Lists = "Lists";
        public const string Member = "Member";
        public const string MemberList = "MemberList";
        public const string MobileError = "MobileError";
        public const string Project = "Project";
        public const string ProjectList = "ProjectList";
        public const string Team = "Team";
        public const string TeamList = "TeamList";
        public const string TestClass = "TestClass";
        public const string TestClassDetail = "TestClassDetail";
        public const string TestClasses = "TestClasses";
        public const string TestClassList = "TestClassList";
        public const string User = "User";
        public const string UserList = "UserList";
    }
}
