//***************************************************************
//This code was generated by a tool but it is ok to hand edit
//as long is what you're adding is a rest resource for an existing command or query
//The file gets rebuilt by building a distinct list of rest resources used
//on commands and queries
//***************************************************************
namespace Core
{
    public class RestResources
    {
        public const string ApplicationSetting = "ApplicationSetting";
        public const string ApplicationSettingDetail = "ApplicationSettingDetail";
        public const string ApplicationSettingList = "ApplicationSettingList";
        public const string ApplicationSettings = "ApplicationSettings";
        public const string CurrentUser = "CurrentUser";
        public const string ErrorDetail = "ErrorDetail";
        public const string ErrorList = "ErrorList";
        public const string Lists = "Lists";
        public const string MobileError = "MobileError";
        public const string UserDetail = "UserDetail";
        public const string UserList = "UserList";
    }
}
