//***************************************************************
//This code was generated by a tool but it is ok to hand edit
//as long is what you're adding is a rest resource for an existing command or query
//The file gets rebuilt by building a distinct list of rest resources used
//on commands and queries
//***************************************************************
namespace Core
{
    public class RestResources
    {
        public const string ApplicationSetting = "ApplicationSetting";
        public const string ApplicationSettingList = "ApplicationSettingList";
        public const string CurrentUser = "CurrentUser";
        public const string Error = "Error";
        public const string ErrorList = "ErrorList";
        public const string Lists = "Lists";
        public const string Member = "Member";
        public const string MemberList = "MemberList";
        public const string MobileError = "MobileError";
        public const string Project = "Project";
        public const string ProjectList = "ProjectList";
        public const string Team = "Team";
        public const string TeamList = "TeamList";
        public const string TestModel = "TestModel";
        public const string TestModelDetail = "TestModelDetail";
        public const string TestModelList = "TestModelList";
        public const string TestModels = "TestModels";
        public const string User = "User";
        public const string UserList = "UserList";
    }
}
