//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
import { HttpClient, HttpResponseMessage } from 'aurelia-http-client';
import { autoinject, inject } from "aurelia-framework";
import * as Models from "./models.generated";
import { MessengerService } from "./services/messenger-service";
import { EncoderService } from "./services/encoder-service";
import { AjaxService } from "./services/ajax-service";

@autoinject()
export class ApplicationSetting
{
    url: string = 'api/ApplicationSetting';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async delete (request: Models.IdRequest):
    Promise<Models.Response>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildDeleteRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}

public async put (request: Models.ApplicationSettingDetail):
Promise<Models.NewItemResponse>
{
    this.messenger.incrementHttpRequestCounter();
    var requestBuilder = await this.ajaxService.buildPutRequest(request, this.url);
    try {
    var response = await requestBuilder.send();
    this.messenger.decrementHttpRequestCounter();
    var out = <Models.IResponse>JSON.parse(response.response);
    this.messenger.showResponseMessage(out);
    return out;
}
catch (err)
{
    this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
    
    var result = {
    isOk: false,
    message: err.statusText
};

this.messenger.decrementHttpRequestCounter();
this.messenger.showResponseMessage(result);
return result;
}
}

public async get (request: Models.IdRequest):
Promise<Models.ResponseOfApplicationSettingDetail>
{
    this.messenger.incrementHttpRequestCounter();
    var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
    try {
    var response = await requestBuilder.send();
    this.messenger.decrementHttpRequestCounter();
    var out = <Models.IResponse>JSON.parse(response.response);
    this.messenger.showResponseMessage(out);
    return out;
}
catch (err)
{
    this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
    
    var result = {
    isOk: false,
    message: err.statusText
};

this.messenger.decrementHttpRequestCounter();
this.messenger.showResponseMessage(result);
return result;
}
}
}
@autoinject()
export class ApplicationSettingList
{
    url: string = 'api/ApplicationSettingList';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.ApplicationSettingListRequest):
    Promise<Models.ApplicationSettingListResponse>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class CurrentUser
{
    url: string = 'api/CurrentUser';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.EmptyRequest):
    Promise<Models.ResponseOfAppPrincipal>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class ErrorDetail
{
    url: string = 'api/ErrorDetail';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.IdRequest):
    Promise<Models.ResponseOfErrorDetail>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class ErrorList
{
    url: string = 'api/ErrorList';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.ErrorListRequest):
    Promise<Models.ErrorListResponse>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class Lists
{
    url: string = 'api/Lists';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.ListsRequest):
    Promise<Models.ListsResponse>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class Member
{
    url: string = 'api/Member';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async delete (request: Models.IdRequest):
    Promise<Models.Response>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildDeleteRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}

public async get (request: Models.IdRequest):
Promise<Models.ResponseOfMemberDetail>
{
    this.messenger.incrementHttpRequestCounter();
    var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
    try {
    var response = await requestBuilder.send();
    this.messenger.decrementHttpRequestCounter();
    var out = <Models.IResponse>JSON.parse(response.response);
    this.messenger.showResponseMessage(out);
    return out;
}
catch (err)
{
    this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
    
    var result = {
    isOk: false,
    message: err.statusText
};

this.messenger.decrementHttpRequestCounter();
this.messenger.showResponseMessage(result);
return result;
}
}

public async put (request: Models.MemberDetail):
Promise<Models.NewItemResponse>
{
    this.messenger.incrementHttpRequestCounter();
    var requestBuilder = await this.ajaxService.buildPutRequest(request, this.url);
    try {
    var response = await requestBuilder.send();
    this.messenger.decrementHttpRequestCounter();
    var out = <Models.IResponse>JSON.parse(response.response);
    this.messenger.showResponseMessage(out);
    return out;
}
catch (err)
{
    this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
    
    var result = {
    isOk: false,
    message: err.statusText
};

this.messenger.decrementHttpRequestCounter();
this.messenger.showResponseMessage(result);
return result;
}
}
}
@autoinject()
export class MemberList
{
    url: string = 'api/MemberList';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.MemberListRequest):
    Promise<Models.MemberListResponse>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class MobileError
{
    url: string = 'api/MobileError';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async post (request: Models.MobileErrorRequest):
    Promise<Models.Response>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildPostRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}
@autoinject()
export class UserDetail
{
    url: string = 'api/UserDetail';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async delete (request: Models.IdRequest):
    Promise<Models.Response>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildDeleteRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}

public async get (request: Models.IdRequest):
Promise<Models.ResponseOfUserDetail>
{
    this.messenger.incrementHttpRequestCounter();
    var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
    try {
    var response = await requestBuilder.send();
    this.messenger.decrementHttpRequestCounter();
    var out = <Models.IResponse>JSON.parse(response.response);
    this.messenger.showResponseMessage(out);
    return out;
}
catch (err)
{
    this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
    
    var result = {
    isOk: false,
    message: err.statusText
};

this.messenger.decrementHttpRequestCounter();
this.messenger.showResponseMessage(result);
return result;
}
}

public async put (request: Models.UserDetail):
Promise<Models.NewItemResponse>
{
    this.messenger.incrementHttpRequestCounter();
    var requestBuilder = await this.ajaxService.buildPutRequest(request, this.url);
    try {
    var response = await requestBuilder.send();
    this.messenger.decrementHttpRequestCounter();
    var out = <Models.IResponse>JSON.parse(response.response);
    this.messenger.showResponseMessage(out);
    return out;
}
catch (err)
{
    this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
    
    var result = {
    isOk: false,
    message: err.statusText
};

this.messenger.decrementHttpRequestCounter();
this.messenger.showResponseMessage(result);
return result;
}
}
}
@autoinject()
export class UserList
{
    url: string = 'api/UserList';
    
    constructor(private ajaxService: AjaxService, private messenger:MessengerService)
    {
    }
    
    public async get (request: Models.UserListRequest):
    Promise<Models.UserListResponse>
    {
        this.messenger.incrementHttpRequestCounter();
        var requestBuilder = await this.ajaxService.buildGetRequest(request, this.url);
        try {
        var response = await requestBuilder.send();
        this.messenger.decrementHttpRequestCounter();
        var out = <Models.IResponse>JSON.parse(response.response);
        this.messenger.showResponseMessage(out);
        return out;
    }
    catch (err)
    {
        this.ajaxService.logError(err, this.url, (<any>new Error()).stack);
        
        var result = {
        isOk: false,
        message: err.statusText
    };
    
    this.messenger.decrementHttpRequestCounter();
    this.messenger.showResponseMessage(result);
    return result;
}
}
}

