//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************
using Fernweh.Core;
using Fernweh.Core.Models.Identity;
namespace Fernweh.Core.Operations.Roles.Extras
{
    public static partial class RoleExtensions
    {
        private static RoleMessage toRoleMessage(Role model, RoleMessage message)
        {
            message.Id = model.Id;
            message.Name = model.Name;
            
            return message;
        }
        public static Role updateFromRoleMessage(RoleMessage message, Role model)
        {
            model.Name =message.Name;
            return model;
        }
        
    }
}

